version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.aladhan
    links:
      - mail
      - mysql
      - memcached
    ports:
      - "8000:80"
      - "8443:443"
      - "10022:22"
    volumes:
      - ./app/:/app/
      - ./:/docker/
    volumes_from:
      - storage
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
      - etc/environment.aladhan.yml
    environment:
      - VIRTUAL_HOST=.app.boilerplate.docker
      - VIRTUAL_PORT=80
      - POSTFIX_RELAYHOST=[mail]:1025


  #######################################
  # MySQL server
  #######################################
  #  mysql:
  #  build:
  #    context: docker/mysql/
  #    #dockerfile: MySQL-5.6.Dockerfile
  #    dockerfile: MySQL-5.7.Dockerfile
  #  ports:
  #    - 13306:3306
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml
  #    - etc/environment.aladhan.yml

  #######################################
  # Memcached
  #######################################
  #memcached:
  #  build:
  #    context: docker/memcached/
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/environment.yml

  #######################################
  # Mail
  #######################################
  # Mailhog
  #mail:
  #   image: mailhog/mailhog
   #  ports:
   #    - 8025:8025
   #   environment:
   #   - VIRTUAL_HOST=mail.boilerplate.docker
   #   - VIRTUAL_PORT=8025

  #######################################
  # phpMyAdmin
  #######################################
  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin
  #  links:
  #    - mysql
  #  environment:
  #    - PMA_HOSTS=mysql
  #    - VIRTUAL_HOST=pma.boilerplate.docker
  #    - VIRTUAL_PORT=80
  #  volumes:
  #    - /sessions

  #######################################
  # Storage
  #######################################
  storage:
    build:
      context: docker/storage/
    volumes:
      - /storage
